### ISSUE TITLE
feat: /health endpoint

### ISSUE THREAD

**Issue by garrettladley** [GenerateNU/nightlife#27]
create a simple `GET` endpoint at `/health` that returns `http.StatusOK` (200)

**Comment by garrettladley** [comment]
why? [Microservices Pattern: Health Check API](https://microservices.io/patterns/observability/health-check-api.html).

tldr: "a health check client - a monitoring service, [service registry](https://microservices.io/patterns/service-registry.html) or load balancer - periodically invokes the endpoint to check the health of the service instance."

**Comment by garrettladley** [comment]
resources:
- [fiber app](https://docs.gofiber.io/api/app/)
- [`app.Get`](https://docs.gofiber.io/api/app/#route-handlers)
- [`fiber.Ctx`](https://docs.gofiber.io/api/ctx)
- [`c.SendStatus`](https://docs.gofiber.io/api/ctx#sendstatus)

**Comment by Benjaspet** [comment]
See (#40).
